global:
    scrape_interval: 10s
    external_labels:
        monitor: node-monitor
scrape_configs:
    - job_name: prometheus
      static_configs:
          - targets:
                - 'localhost:9090'
    - job_name: node-monitor
      fallback_scrape_protocol: PrometheusText0.0.4
      static_configs:
          - targets:
                - 'node:9100'
            labels:
                alias: block-producer-node
                type: cardano-node
          - targets:
                - 'node:12798'
            labels:
                alias: block-producer-node
                type: cardano-node
