{
 "title": "Cardano Mithril Signer",
 "description": "Mithril signer metrics dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "signers", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  { "title": "${signers}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "signers" },
  {
   "title": "Signer Registration Last Epoch",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mithril_signer_signer_registration_success_last_epoch",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signer Registration Success",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(increase(mithril_signer_signer_registration_success_since_startup[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signer Registration Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(increase(mithril_signer_signer_registration_total_since_startup[$__range])-increase(mithril_signer_signer_registration_success_since_startup[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signer Registration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mithril_signer_signer_registration_total_since_startup",
     "legendFormat": "total"
    },
    {
     "expr": "mithril_signer_signer_registration_success_since_startup",
     "legendFormat": "success"
    },
    {
     "expr": "mithril_signer_signer_registration_total_since_startup-mithril_signer_signer_registration_success_since_startup",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "Signature Registration Last Epoch",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mithril_signer_signature_registration_success_last_epoch",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signature Registration Success",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(increase(mithril_signer_signature_registration_success_since_startup[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signature Registration Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(increase(mithril_signer_signature_registration_total_since_startup[$__range])-increase(mithril_signer_signature_registration_success_since_startup[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Signature Registration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mithril_signer_signature_registration_total_since_startup",
     "legendFormat": "total"
    },
    {
     "expr": "mithril_signer_signature_registration_success_since_startup",
     "legendFormat": "success"
    },
    {
     "expr": "mithril_signer_signature_registration_total_since_startup-mithril_signer_signature_registration_success_since_startup",
     "legendFormat": "error"
    }
   ]
  },
  {
   "title": "State Machine Cycles",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(increase(mithril_signer_runtime_cycle_total_since_startup[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Machine Cycles Success",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(increase(mithril_signer_runtime_cycle_success_since_startup[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Machine Cycles Errors",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(increase(mithril_signer_runtime_cycle_total_since_startup[$__range])-increase(mithril_signer_runtime_cycle_success_since_startup[$__range]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "State Machine Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100*(1-(mithril_signer_runtime_cycle_total_since_startup-mithril_signer_runtime_cycle_success_since_startup)/mithril_signer_runtime_cycle_total_since_startup)",
     "legendFormat": "success rate"
    }
   ]
  }
 ]
}