{
 "title": "Cardano SPO - Mainnet",
 "description": "Cardano Pool Monitor",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "relays", "query": { "query": "label_values(alias)" } }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "grafana-clock-panel",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Current Epoch Progress",
   "type": "gauge",
   "description": "Slot height in current epoch (taken from Core node)",
   "gridPos": { "h": 4, "w": 4, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotInEpoch_int{alias=\"block-producer-node\"}/432000 ",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "Pool Performance",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_Forge_node_not_leader_int{alias=\"block-producer-node\"} + cardano_node_metrics_Forge_adopted_int{alias=\"block-producer-node\"}) / cardano_node_metrics_Forge_forge_about_to_lead_int{alias=\"block-producer-node\"} * 100",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "KES Key : Days Left",
   "type": "gauge",
   "description": "Remaining KES DAYS before we need to rotate keys",
   "gridPos": { "h": 4, "w": 4, "x": 11, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(cardano_node_metrics_remainingKESPeriods_int{alias=\"block-producer-node\"} * 1.5)",
     "legendFormat": "{{none}}"
    }
   ]
  },
  {
   "title": "KES Key Rotation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_currentKESPeriod_int{alias=\"block-producer-node\"}",
     "legendFormat": "Current"
    },
    {
     "expr": "cardano_node_metrics_operationalCertificateExpiryKESPeriod_int{alias=\"block-producer-node\"}",
     "legendFormat": "Expiry"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_epoch_int{alias=\"block-producer-node\"}",
     "legendFormat": "Epoch"
    },
    {
     "expr": "cardano_node_metrics_blockNum_int{alias=\"block-producer-node\"}",
     "legendFormat": "Block height"
    },
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"block-producer-node\"}",
     "legendFormat": "Slot height"
    }
   ]
  },
  {
   "title": "Activestake",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(data_liveStake{alias=\"relay-node-1\"}/1000000)"
    }
   ]
  },
  {
   "title": "Pledged",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "round(data_activePledge{alias=\"relay-node-1\"}/1000000)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Saturation",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "data_saturationLevel{alias=\"relay-node-1\"}"
    }
   ]
  },
  {
   "title": "Rewards",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "data_interest{alias=\"relay-node-1\"}"
    }
   ]
  },
  {
   "title": "Leader schedule",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "expr": "cardano_node_metrics_slotNum_int{alias=\"relay-node-1\"}   ",
     "legendFormat": "Slot"
    },
    {
     "decimalSeparator": ".",
     "delimiter": ",",
     "schema": [
      { "name": "Time", "type": "time" },
      { "name": "Slot", "type": "number" }
     ]
    }
   ]
  },
  {
   "title": "Forge Slots",
   "type": "stat",
   "description": "Stats since last node restart",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_Forge_node_is_leader_int{alias=\"block-producer-node\"}",
     "legendFormat": "Slots Leader"
    },
    {
     "expr": "cardano_node_metrics_Forge_adopted_int{alias=\"block-producer-node\"}",
     "legendFormat": "Slots adopted"
    }
   ]
  },
  {
   "title": "Blocks Epoch",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "data_currentEpochBlocks{alias=\"relay-node-1\"}"
    }
   ]
  },
  {
   "title": "Blocks Minted",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "data_lifetimeBlocks{alias=\"relay-node-1\"}"
    }
   ]
  },
  { "title": "Producer", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Core Node System Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "node_load1{alias=\"block-producer-node\"}*100",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{alias=\"block-producer-node\"}*100",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{alias=\"block-producer-node\"}*100",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Core Node System Health",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"block-producer-node\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"block-producer-node\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"block-producer-node\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"block-producer-node\"} / (node_memory_MemTotal_bytes{alias=\"block-producer-node\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "(1- (node_memory_SwapFree_bytes{alias=\"block-producer-node\"} / node_memory_SwapTotal_bytes{alias=\"block-producer-node\"})) * 100",
     "legendFormat": "SWAP"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Core node uptime",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rts_gc_wall_ms{alias=\"block-producer-node\"} / (1000)",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "description": "Connected incoming peers to Core Node",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_incomingConns{alias=\"block-producer-node\"}",
     "legendFormat": "{{alias}}"
    }
   ]
  },
  {
   "title": "TX's processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"block-producer-node\"}",
     "legendFormat": "Core"
    }
   ]
  },
  { "title": "Relay - $relays", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 }, "repeat": "relays" },
  {
   "title": "Relay Node System Load",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "node_load1{alias=\"$relays\"}*100",
     "legendFormat": "Load 1m"
    },
    {
     "expr": "node_load5{alias=\"$relays\"}*100",
     "legendFormat": "Load 5m"
    },
    {
     "expr": "node_load15{alias=\"$relays\"}*100",
     "legendFormat": "Load 15m"
    }
   ]
  },
  {
   "title": "Relay Node System Health",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg by(alias) (irate(node_cpu_seconds_total{mode=\"idle\",alias=\"$relays\"}[1m])) * 100)",
     "legendFormat": "CPU"
    },
    {
     "expr": "100 - ((node_filesystem_avail_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"$relays\"} * 100) / node_filesystem_size_bytes{mountpoint=\"/\",fstype!=\"rootfs\",alias=\"$relays\"})",
     "legendFormat": "Disk"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"$relays\"} / (node_memory_MemTotal_bytes{alias=\"$relays\"})))* 100",
     "legendFormat": "RAM"
    },
    {
     "expr": "(1- (node_memory_SwapFree_bytes{alias=\"$relays\"} / node_memory_SwapTotal_bytes{alias=\"$relays\"})) * 100",
     "legendFormat": "SWAP"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Relay node 1 uptime",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rts_gc_wall_ms{alias=\"$relays\"} / (1000)",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "Peers",
   "type": "stat",
   "description": "Connected peers to Relay 1",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_connectionManager_incomingConns{alias=\"$relays\"}",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "TX's processed",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "cardano_node_metrics_txsProcessedNum_int{alias=\"$relays\"}",
     "legendFormat": "Relay1"
    }
   ]
  },
  {
   "title": "Blockchain stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mempool Transactions",
     "type": "timeseries",
     "description": "current",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 790 },
     "fieldConfig": { "defaults": { "unit": "tx" } },
     "targets": [
      {
       "expr": "cardano_node_metrics_txsInMempool_int{alias=\"block-producer-node\"}",
       "legendFormat": "Core"
      },
      {
       "expr": "cardano_node_metrics_txsInMempool_int{alias=~\"$relays\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Block Sync Speed (blocks / min)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 790 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate (cardano_node_metrics_blockNum_int{alias=\"block-producer-node\"}[150s]) *60",
       "legendFormat": "Core"
      },
      {
       "expr": "rate (cardano_node_metrics_blockNum_int{alias=~\"$relays\"}[150s]) *60",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Chain Density",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 796 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "cardano_node_metrics_density_real{alias=\"block-producer-node\"} * 100",
       "legendFormat": "Core"
      },
      {
       "expr": "cardano_node_metrics_density_real{alias=~\"$relays\"} * 100",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Block height",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 796 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "cardano_node_metrics_blockNum_int{alias=\"block-producer-node\"}",
       "legendFormat": "Core"
      },
      {
       "expr": "cardano_node_metrics_blockNum_int{alias=~\"$relays\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Slot Height",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 796 },
     "fieldConfig": { "defaults": { "unit": "locale" } },
     "targets": [
      {
       "expr": "cardano_node_metrics_slotNum_int{alias=\"block-producer-node\"}",
       "legendFormat": "Core"
      },
      {
       "expr": "cardano_node_metrics_slotNum_int{alias=~\"$relays\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Device stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "Aggregate Data Transfer",
     "type": "timeseries",
     "description": "1 hour rolling window",
     "gridPos": { "h": 6, "w": 24, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(node_network_receive_bytes_total{alias=\"block-producer-node\"}[1h]) * 3600",
       "legendFormat": "Core - {{device}}"
      },
      {
       "expr": "rate(node_network_receive_bytes_total{alias=~\"$relays\"}[1h]) * 3600",
       "legendFormat": "{{alias}} - {{device}}"
      }
     ]
    },
    {
     "title": "Memory Utilization ",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{alias=\"block-producer-node\"} / (node_memory_MemTotal_bytes{alias=\"block-producer-node\"})))* 100",
       "legendFormat": "Core"
      },
      {
       "expr": "(1 - (node_memory_MemAvailable_bytes{alias=~\"$relays\"} / (node_memory_MemTotal_bytes{alias=~\"$relays\"})))* 100",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Peak Memory Allocated",
     "type": "timeseries",
     "description": "Counts only memory that is physically free (from OS, in MBytes)",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "rts_gc_peak_megabytes_allocated{alias=\"block-producer-node\"}",
       "legendFormat": "Core"
      },
      {
       "expr": "rts_gc_peak_megabytes_allocated{alias=~\"$relays\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Current \"Residency\" (amount of live data)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "rts_gc_current_bytes_used{alias=\"block-producer-node\"}/(1024*1024)",
       "legendFormat": "Core"
      },
      {
       "expr": "rts_gc_current_bytes_used{alias=~\"$relays\"}/(1024*1024)",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Max \"Residency\"",
     "type": "timeseries",
     "description": "Amount of live data, MBytes",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "rts_gc_max_bytes_used{alias=\"block-producer-node\"} /(1024*1024)",
       "legendFormat": "Core"
      },
      {
       "expr": "rts_gc_max_bytes_used{alias=~\"$relays\"} /(1024*1024)",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "File Descriptors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "node_filefd_allocated{alias=\"block-producer-node\"}",
       "legendFormat": "Core"
      },
      {
       "expr": "node_filefd_allocated{alias=~\"$relays\"}",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "RSS (allocated memory in RAM)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "(cardano_node_metrics_Mem_resident_int{alias=\"block-producer-node\"})/(1024*1024)",
       "legendFormat": "Core"
      },
      {
       "expr": "(cardano_node_metrics_Mem_resident_int{alias=~\"$relays\"})/(1024*1024)",
       "legendFormat": "{{alias}}"
      }
     ]
    },
    {
     "title": "Time Synchronization (Core Node)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_timex_estimated_error_seconds{alias=\"block-producer-node\"}",
       "legendFormat": "Est. error(s)"
      },
      {
       "expr": "node_timex_offset_seconds{alias=\"block-producer-node\"}",
       "legendFormat": "Offset: Node vs. Ref."
      },
      {
       "expr": "node_timex_maxerror_seconds{alias=\"block-producer-node\"}",
       "legendFormat": "Max. Error (s)"
      }
     ]
    },
    {
     "title": "Time Synchronization ($relays)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
     "repeat": "relays",
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "node_timex_estimated_error_seconds{alias=\"$relays\"}",
       "legendFormat": "Est. error(s)"
      },
      {
       "expr": "node_timex_offset_seconds{alias=\"$relays\"}",
       "legendFormat": "Offset: Node vs. Ref."
      },
      {
       "expr": "node_timex_maxerror_seconds{alias=\"$relays\"}",
       "legendFormat": "Max. Error (s)"
      }
     ]
    }
   ]
  }
 ]
}