global:
  scrape_interval: 10s
  external_labels:
    monitor: 'node-monitor'

scrape_configs:
  - job_name: 'mithril-signers'
    static_configs:
      - targets: [ 'localhost:9091' ]

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9100']
        labels:
          alias: 'block-producer-node'
          type:  'cardano-node'

      - targets: ['localhost:12798']
        labels:
          alias: 'block-producer-node'
          type:  'cardano-node'
