services:
  cardano-node:
    image: ${CARDANO_IMAGE}
    platform: linux/amd64
    restart: unless-stopped
    container_name: cardano-node
    ports:
      - "3001:3001"
    environment:
      - NETWORK=${CARDANO_NETWORK}
      - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
    volumes:
      - cardano-ipc:/ipc
      - ${CARDANO_DATA_DIR}:/data
  postgres:
    image: postgres:15.3
    platform: linux/amd64
    container_name: db-sync-postgres
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT_FORWARD}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
  cardano-db-sync:
    image: ghcr.io/intersectmbo/cardano-db-sync:13.6.0.5-preview-fix-1
    platform: linux/amd64
    container_name: cardano-db-sync
    restart: unless-stopped
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - NETWORK=${CARDANO_NETWORK}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - cardano-ipc:/node-ipc
      - db-sync-data:/var/lib
  cardano-ogmios:
    image: cardanosolutions/ogmios:v6.11.0
    platform: linux/amd64
    container_name: cardano-ogmios
    restart: unless-stopped
    environment:
      - DATA_DIR=/data
    ports:
      - "1337:1337"
    volumes:
      - cardano-ipc:/ipc
      - ogmios-data:/data
    command:
      - --node-socket
      - /ipc/node.socket
      - --node-config
      - /config/${CARDANO_NETWORK}/cardano-node/config.json
      - --host
      - 0.0.0.0
volumes:
    cardano-ipc: {}
    db-sync-data: {}
    postgres-data: {}
    ogmios-data: {}
